export const DEMO_RESULT = {
  isAreaMode: true,
  geo: {
    lat: 45.4215, lon: -75.6972,
    displayName: 'Ottawa, Ontario, Canada',
    userCity: 'Ottawa', userCountry: 'Canada', userState: 'Ontario', userStreet: '',
    address: { city: 'Ottawa', state: 'Ontario', country: 'Canada', postcode: 'K1P' },
  },
  weather: {
    current: { temperature_2m: 4, weather_code: 3 },
  },
  climate: {
    avgHighC: 11, avgLowC: -1, avgPrecipMm: 2.8,
  },
  knownFacts: {},
  realData: {
    isAreaMode: true,
    areaMetrics: {
      medianPrice: 649000, avgPrice: 712000,
      priceRange: { low: 389000, high: 980000 },
      medianDOM: 22, count: 214,
      priceVolatility: 0.18,
      slowListingPct: 14, fastListingPct: 31,
    },
    areaRiskScore: {
      score: 68,
      label: 'Transitional Market',
      color: '#fbbf24',
      emoji: '🟡',
      factors: [
        { label: 'Stable pricing', impact: 0, icon: '✅' },
        { label: 'Normal market pace (22 days)', impact: 0, icon: '✅' },
        { label: '31% of homes sell in <2 weeks', impact: 5, icon: '🚀' },
      ],
    },
    marketTemperature: { label: 'Balanced Market', color: '#a78bfa' },
    neighborhoodScores: {
      walkScore: 72, transitScore: 65, schoolScore: 81,
      walkability: 72, transit: 65, schools: 81, parks: 78, groceries: 84,
    },
    riskData: {
      overall: { score: 3.2, label: 'Low' },
      hazards: {
        riverine_flooding: { score: 1.1, label: 'Low' },
        wildfire: { score: 0.6, label: 'Low' },
        earthquake: { score: 0.4, label: 'Low' },
        strong_wind: { score: 2.8, label: 'Low' },
      },
      airQuality: { pm25Percentile: 28 },
    },
    newsData: {
      city: 'Ottawa',
      articles: [
        { title: 'Ottawa condo market softens as inventory rises in 2025', source: 'Ottawa Citizen', url: '#', date: '2025-02-10' },
        { title: 'Centretown sees renewed buyer interest after rate cuts', source: 'CBC Ottawa', url: '#', date: '2025-01-28' },
        { title: 'Gatineau vs Ottawa: where first-time buyers are actually buying', source: 'Ottawa Citizen', url: '#', date: '2025-01-15' },
      ],
    },
  },
  ai: {
    areaIntelligence: {
      verdict: 'Good',
      verdictReason: 'Stable government employment base, reasonable prices, and low natural risk make Ottawa a reliable long-term market.',
      stabilityScore: 68,
      marketConditions: 'Ottawa is a balanced market as of early 2025. The government employment base provides a meaningful price floor — federal job stability insulates the market from the volatility seen in Toronto or Vancouver. Median days on market sits at 22, and 31% of listings move within 14 days, signalling genuine buyer demand without the frenzy of a hot market.',
      priceTrend: 'Prices are flat to modestly down (-2 to -4%) from their 2022 peak, partially recovered through 2024. The $649,000 median reflects a market that corrected without collapsing. Condos have softened more than detached homes, where supply remains tight.',
      investmentOutlook: 'Moderate long-term upside. Immigration-driven population growth and persistent new construction shortfall support prices over a 3-5 year horizon.',
      risks: ['Federal public sector dependency — government restructuring could reduce demand', 'Mortgage renewals at higher rates through 2025-2026', 'Condo market softer than detached homes'],
      upsides: ['Stable government employment base provides price floor', 'Strong school ratings across central neighbourhoods', 'Lower volatility than Toronto or Vancouver', 'Growing tech sector diversifying beyond government'],
      liveability: 'High. Walkability scores of 72 in central neighbourhoods, strong parks and greenspace.',
      bestFor: 'Government employees, families prioritising school quality, risk-averse investors',
    },
    propertyEstimate: {
      estimatedValueUSD: 649000,
      pricePerSqftUSD: 412,
      rentEstimateMonthlyUSD: 1820,
      confidenceLevel: 'medium',
      confidenceScore: 62,
      compsUsed: 214,
      priceRange: { low: 520000, high: 780000 },
      priceContext: 'Based on 214 active listings in the Ottawa area. Median price of CA$649,000 reflects a stable market that corrected from its 2022 peak.',
    },
    costOfLiving: {
      monthlyBudgetUSD: 3200,
      groceriesMonthlyUSD: 480,
      transportMonthlyUSD: 160,
      utilitiesMonthlyUSD: 220,
      diningOutMonthlyUSD: 340,
      indexVsUSAverage: 108,
      summary: 'Ottawa is moderately expensive — roughly 8% above the US average. Housing dominates the budget, with groceries and utilities at near-average levels.',
    },
    neighborhood: {
      walkScore: 72,
      transitScore: 65,
      safetyRating: 74,
      schoolRating: 81,
      character: 'A stable, bilingual capital city with a strong government employment base and growing tech sector. Central neighbourhoods are walkable and family-friendly, with the Glebe and Westboro being the most sought-after.',
      pros: ['Strong schools', 'Safe neighbourhoods', 'Rideau Canal'],
      cons: ['Cold winters', 'Government-dependent economy'],
      bestFor: 'Families, government employees, risk-averse buyers',
    },
    investment: {
      rentYieldPercent: 3.4,
      investmentScore: 64,
      appreciationOutlook: 'neutral',
      appreciationOutlookText: 'Moderate long-term appreciation expected as rates stabilise and supply remains constrained.',
      investmentSummary: 'Solid long-term hold. Not a high-growth market but one of the most stable in Canada. Best for buy-and-hold rather than flipping.',
    },
    localInsights: {
      knownFor: 'A federal government town with a growing private sector and genuinely liveable neighbourhoods.',
      topAttractions: ['Rideau Canal (skating in winter, cycling in summer)', 'ByWard Market', 'Parliament Hill', 'Gatineau Park'],
      localTip: 'The Glebe and Westboro command premium prices but hold value well. Vanier and Hintonburg offer better entry prices with improving amenities.',
      languageNote: 'Bilingual city — French services widely available, especially in Gatineau across the river.',
    },
    priceHistory: {
      currency: 'CAD',
      currencySymbol: 'CA$',
      marketNote: 'Ottawa prices surged through 2021-2022 driven by pandemic demand and low rates, then corrected 12-15% through 2023. The market has stabilised in 2024-2025 with modest recovery, and modest appreciation is expected through 2026-2027.',
      data: [
        { year: 2019, value: 430000, type: 'historical' },
        { year: 2020, value: 480000, type: 'historical' },
        { year: 2021, value: 580000, type: 'historical' },
        { year: 2022, value: 740000, type: 'historical' },
        { year: 2023, value: 650000, type: 'historical' },
        { year: 2024, value: 635000, type: 'historical' },
        { year: 2025, value: 649000, type: 'historical' },
        { year: 2026, value: 672000, type: 'projected' },
        { year: 2027, value: 695000, type: 'projected' },
      ],
    },
    riskData: null,
    floorPlan: { typicalSqft: 1450, typicalBeds: 3, typicalBaths: 2 },
  },
}
