export const DEMO_RESULT = {
  geo: {
    displayName: 'Toronto, Ontario, Canada',
    city: 'Toronto',
    province: 'Ontario',
    lat: 43.6532,
    lon: -79.3832,
  },
  weather: {
    temperature: 12,
    condition: 'Partly Cloudy',
    humidity: 58,
    windSpeed: 18,
  },
  climate: {
    avgSummerTemp: 27,
    avgWinterTemp: -5,
    annualRainfallMM: 831,
    snowDaysPerYear: 42,
  },
  neighborhood: {
    walkScore: 87,
    transitScore: 92,
    schoolScore: 74,
    safetyScore: 68,
    walkLabel: "Walker's Paradise",
    transitLabel: 'Excellent Transit',
    schoolLabel: 'Above Average',
    safetyLabel: 'Moderate',
  },
  est: {
    medianValue: 1_050_000,
    pricePerSqft: 924,
    rentPerMonth: 2_650,
    confidence: 89,
    compsAnalyzed: 31,
  },
  investment: {
    score: 74,
    verdict: {
      label: 'BUY',
      confidence: 'High',
      riskLevel: 'Low',
    },
    roiEstimate: null,
    priceTrajectory: null,
  },
  costOfLiving: {
    index: 118,
    rentAvg: 2650,
    groceries: 520,
    transport: 156,
    utilities: 180,
    summary: 'Cost of living is above the national average, driven by housing costs.',
  },
  priceHistory: {
    data: [
      { year: 2022, medianPrice: 920_000 },
      { year: 2023, medianPrice: 960_000 },
      { year: 2024, medianPrice: 1_010_000 },
      { year: 2025, medianPrice: 1_050_000 },
    ],
    projections: null,
  },
  marketHeat: 'hot',
  risk: null,
  aiSummary: null,
  isDeterministic: true,
}
