import { useEffect } from 'react'

const SECTIONS = [
  { title: '1. Acceptance of Terms and Binding Agreement', body: 'By registering an account, accessing, browsing, or otherwise using the Dwelling platform, its website, mobile applications, or any related service (collectively, the "Platform"), you ("User," "you," or "your") acknowledge that you have read, understood, and agree to be legally bound by these Terms and Conditions ("Terms"). If you do not agree to every provision of these Terms, you must immediately discontinue all use of the Platform. These Terms constitute a legally binding agreement between you and Dwelling ("Company," "we," "us," or "our"). The Company reserves the right to amend, update, or replace these Terms at any time without prior individual notice. Updated Terms will be posted on the Platform with a revised effective date. Your continued access to or use of the Platform following any modification constitutes your unconditional acceptance of the revised Terms.' },
  { title: '2. Eligibility and Account Registration', body: 'The Platform is intended for individuals who are at least 18 years of age and who have the legal capacity to enter into binding contracts under applicable law. By using the Platform you represent and warrant that you meet these requirements. You agree to provide accurate, current, and complete information during registration and to update such information as necessary. You are solely responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. The Company is not liable for any loss or damage arising from your failure to maintain account security. The Company reserves the right to refuse registration or cancel accounts at its sole discretion, including where it suspects fraudulent, abusive, or unauthorized use.' },
  { title: '3. No Professional, Financial, Legal, or Real Estate Advice', body: 'ALL INFORMATION, REPORTS, SCORES, ESTIMATES, ANALYSES, VERDICTS, PROJECTIONS, AND OTHER CONTENT PROVIDED BY THE PLATFORM ARE PROVIDED SOLELY FOR GENERAL INFORMATIONAL AND EDUCATIONAL PURPOSES. NOTHING ON THE PLATFORM CONSTITUTES, OR SHOULD BE CONSTRUED AS, FINANCIAL ADVICE, INVESTMENT ADVICE, REAL ESTATE ADVICE, LEGAL ADVICE, TAX ADVICE, MORTGAGE ADVICE, APPRAISAL SERVICES, OR ANY OTHER FORM OF PROFESSIONAL ADVICE. The Company is not a licensed real estate brokerage, mortgage broker, financial institution, investment dealer, securities adviser, appraiser, or legal practitioner in any jurisdiction. No content on the Platform creates any professional-client relationship of any kind. You should independently verify all Platform content and consult with appropriately licensed and qualified professionals before making any real estate, financial, investment, or other significant decision. Reliance on Platform content without independent professional advice is done entirely at your own risk.' },
  { title: '4. Accuracy, Completeness, and Reliability of Data', body: 'THE COMPANY MAKES NO REPRESENTATIONS, WARRANTIES, OR GUARANTEES OF ANY KIND, EXPRESS OR IMPLIED, REGARDING THE ACCURACY, COMPLETENESS, TIMELINESS, RELIABILITY, SUITABILITY, OR AVAILABILITY OF ANY PLATFORM CONTENT. Real estate markets, property values, rental rates, interest rates, demographic data, risk scores, and all other information are subject to rapid and unpredictable change. Platform content may be based on data from third-party sources outside the Company\'s control and may be inaccurate, incomplete, delayed, or unavailable. Algorithmic valuations, investment scores, stability scores, and market indicators are statistical approximations that may differ materially from actual market conditions or professional appraisals. The Company expressly disclaims all liability of any kind arising from or in connection with reliance on any Platform content.' },
  { title: '5. AI-Generated Content — Special Disclaimer', body: 'The Platform uses large language model artificial intelligence systems to generate reports, city analyses, verdicts, investment summaries, neighbourhood descriptions, risk assessments, and other content. You acknowledge and agree that: (a) AI-generated content is produced algorithmically and may contain factual errors, logical inconsistencies, hallucinations, or outdated information; (b) AI investment scores and outlooks are NOT predictions, forecasts, or guarantees of future real estate performance; (c) AI-generated content reflects the state of training data and available inputs at the time of generation and does not account for all factors relevant to real estate decisions; (d) the Company does not review or verify the accuracy of AI-generated output before it is displayed; (e) AI-generated content should never be the sole or primary basis for any financial or real estate decision; and (f) the Company is not liable for any loss, damage, or harm resulting from use of or reliance on AI-generated content. The use of AI by the Platform is experimental and subject to significant inherent limitations.' },
  { title: '6. Limitation of Liability', body: 'TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE COMPANY, ITS OFFICERS, DIRECTORS, SHAREHOLDERS, EMPLOYEES, CONTRACTORS, AGENTS, SUCCESSORS, OR ASSIGNS BE LIABLE FOR ANY: (A) INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES; (B) LOSS OF PROFITS, REVENUE, BUSINESS, GOODWILL, DATA, OR ANTICIPATED SAVINGS; (C) LOSS ARISING FROM REAL ESTATE TRANSACTIONS, INVESTMENT DECISIONS, OR FINANCIAL LOSSES OF ANY KIND; (D) COST OF SUBSTITUTE GOODS OR SERVICES; OR (E) ANY OTHER LOSS OR DAMAGE OF ANY KIND, WHETHER BASED ON CONTRACT, TORT (INCLUDING NEGLIGENCE), STATUTE, OR OTHERWISE, EVEN IF THE COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THE TOTAL AGGREGATE LIABILITY OF THE COMPANY FOR ALL CLAIMS SHALL NOT EXCEED THE GREATER OF: (I) THE TOTAL FEES ACTUALLY PAID BY YOU IN THE THREE CALENDAR MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM; OR (II) TWENTY-FIVE CANADIAN DOLLARS (CAD $25.00).' },
  { title: '7. No Warranty', body: 'THE PLATFORM AND ALL PLATFORM CONTENT ARE PROVIDED ON AN "AS IS," "AS AVAILABLE," AND "WITH ALL FAULTS" BASIS. THE COMPANY EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO: IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT; WARRANTIES THAT THE PLATFORM WILL MEET YOUR REQUIREMENTS; WARRANTIES THAT THE PLATFORM WILL BE AVAILABLE, UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE; AND WARRANTIES REGARDING THE ACCURACY OR RELIABILITY OF ANY INFORMATION OBTAINED THROUGH THE PLATFORM. NO ORAL OR WRITTEN ADVICE OR INFORMATION OBTAINED FROM THE COMPANY CREATES ANY WARRANTY NOT EXPRESSLY STATED IN THESE TERMS.' },
  { title: '8. Subscription, Billing, and Cancellation Policy', body: 'Paid subscriptions ("Pro Plan") are billed in advance on a monthly or annual basis in Canadian dollars (CAD). By subscribing, you authorize the Company to charge your payment method on a recurring basis at the applicable rate until cancelled. ALL SUBSCRIPTION FEES ARE STRICTLY NON-REFUNDABLE. The Company does not offer refunds, credits, or prorated amounts for any reason whatsoever, including but not limited to: partial use of a billing period, dissatisfaction with Platform content, service interruptions, feature changes, or account termination for breach of these Terms. Subscriptions renew automatically at the end of each billing period unless cancelled prior to the renewal date. To cancel, you must do so through your account settings or by contacting the Company at 01dominique.c@gmail.com before the next billing date. Cancellation takes effect at the end of the then-current billing period; you retain Pro access until that date. No partial-period credits are issued upon cancellation. The Company reserves the right to change pricing at any time with no more than thirty (30) days notice; continued use after a price change constitutes acceptance of new pricing. Free-tier usage limits are set at the Company\'s sole discretion and may be changed at any time.' },
  { title: '9. User Obligations and Prohibited Conduct', body: 'You agree to use the Platform only for lawful purposes. You shall not: (a) use the Platform for fraudulent or unauthorized purposes; (b) scrape, harvest, or systematically extract any Platform data without written permission; (c) reproduce, distribute, sublicense, sell, or commercially exploit any Platform content; (d) reverse engineer, decompile, or disassemble the Platform; (e) circumvent any security or access control mechanism; (f) impersonate any person or entity; (g) transmit any virus, malware, or harmful code; (h) attempt unauthorized access to any part of the Platform or its infrastructure; (i) use automated bots or scripts in ways not expressly permitted; or (j) interfere with other users\' enjoyment of the Platform. Violation may result in immediate account termination and pursuit of all available legal remedies.' },
  { title: '10. Intellectual Property Rights', body: 'The Platform and all content, features, functionality, design, code, databases, trademarks, and logos (collectively, "Company IP") are owned by the Company or its licensors and are protected by Canadian and international intellectual property laws. You are granted a limited, personal, non-exclusive, non-transferable, revocable licence to access and use the Platform solely for personal, non-commercial informational purposes, subject to compliance with these Terms. This licence does not include the right to sublicense, sell, modify, create derivative works from, or publicly distribute any Company IP. Unauthorized use of Company IP terminates this licence immediately.' },
  { title: '11. Privacy and Data Handling', body: 'By using the Platform, you consent to the collection, use, storage, and processing of your personal information as described in the Company\'s Privacy Policy. The Company collects your email address, authentication credentials (in hashed form), account activity, and usage counts. Search queries are processed in real time and not retained as personally identifiable records. Your third-party API key, if stored, is encoded and used solely to forward AI inference requests on your behalf. The Company does not sell your personal information. The Company complies with applicable Canadian privacy legislation including PIPEDA and applicable provincial privacy laws.' },
  { title: '12. Third-Party Services and Data Sources', body: 'The Platform relies on third-party data providers and infrastructure services including Statistics Canada, OpenStreetMap contributors, Open-Meteo, Cerebras AI, Turso, Vercel Inc., and real estate data aggregators. The Company does not control, endorse, or guarantee the accuracy or availability of any third-party service. The Company is not affiliated with or officially endorsed by any third-party provider. Interruption or inaccuracy of any third-party service may affect Platform functionality without liability to the Company.' },
  { title: '13. Account Suspension and Termination', body: 'The Company may, at its sole discretion and without notice or liability, suspend or permanently terminate your account for any reason, including breach of these Terms, fraudulent or abusive conduct, non-payment, or any conduct the Company believes may expose it to legal liability. Upon termination: (a) your access to the Platform immediately ceases; (b) you remain liable for all obligations incurred prior to termination; (c) no subscription fees or portion thereof will be refunded; and (d) all provisions of these Terms that by their nature should survive termination shall survive.' },
  { title: '14. Indemnification', body: 'To the fullest extent permitted by law, you agree to defend, indemnify, and hold harmless the Company and its officers, directors, shareholders, employees, contractors, agents, licensors, successors, and assigns from and against any and all claims, liabilities, damages, judgments, losses, costs, expenses, and legal fees arising out of or relating to: (a) your use of the Platform; (b) your violation of these Terms; (c) your violation of any applicable law or third-party right; (d) your reliance on any Platform content for any decision; or (e) any content or information you submit through the Platform.' },
  { title: '15. Dispute Resolution, Arbitration, and Class Action Waiver', body: 'PLEASE READ THIS SECTION CAREFULLY — IT AFFECTS YOUR LEGAL RIGHTS. These Terms are governed exclusively by the laws of the Province of Ontario and the applicable federal laws of Canada, without regard to conflict of law principles. Before initiating formal proceedings, the parties agree to attempt resolution through good-faith negotiation for thirty (30) days following written notice. If unresolved, the Dispute shall be finally resolved by binding arbitration in Ottawa, Ontario under the Arbitration Act, 1991 (Ontario) before a single arbitrator. The arbitrator\'s decision shall be final and binding. YOU AND THE COMPANY EACH WAIVE ANY RIGHT TO A JURY TRIAL. YOU WAIVE ANY RIGHT TO INITIATE OR PARTICIPATE IN ANY CLASS ACTION, COLLECTIVE ACTION, OR REPRESENTATIVE PROCEEDING OF ANY KIND AGAINST THE COMPANY. The Company may seek injunctive or equitable relief in any court of competent jurisdiction to protect its intellectual property or prevent irreparable harm.' },
  { title: '16. Modifications to the Platform', body: 'The Company reserves the right, at its sole discretion, to modify, suspend, or discontinue the Platform or any part thereof at any time, with or without notice; add, remove, or change features or content; change pricing upon reasonable notice; or impose usage limits. The Company shall not be liable for any modification, suspension, or discontinuation of the Platform.' },
  { title: '17. Severability, Waiver, and Entire Agreement', body: 'If any provision of these Terms is held invalid, illegal, or unenforceable, it shall be modified to the minimum extent necessary to make it enforceable, and the remaining provisions shall continue in full force. No waiver by the Company of any breach shall be deemed a waiver of any subsequent breach. These Terms, together with the Privacy Policy and any other policies incorporated herein by reference, constitute the entire agreement between you and the Company regarding the Platform and supersede all prior understandings, agreements, and representations.' },
  { title: '18. Contact and Legal Notices', body: 'For general support: 01dominique.c@gmail.com. For formal legal notices, written notice must be sent to the same address with the subject line "Legal Notice — Dwelling" and must include: your full legal name, account email, a detailed description of the claim, and the relief sought. The Company will acknowledge receipt of formal legal notices within ten (10) business days. These Terms were last updated on March 30, 2026.' },
]

export default function TermsModal({ onClose }) {
  useEffect(() => {
    const prev = document.body.style.overflow
    document.body.style.overflow = 'hidden'
    return () => { document.body.style.overflow = prev }
  }, [])
  return (
    <div onClick={onClose} style={{ position: 'fixed', inset: 0, zIndex: 1000, background: 'rgba(0,0,0,0.92)', backdropFilter: 'blur(8px)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 20 }}>
      <div onClick={e => e.stopPropagation()}
        className="liquid-glass-strong" style={{ borderRadius: 24, maxWidth: 700, width: '100%', height: '82vh', display: 'flex', flexDirection: 'column' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '20px 28px', borderBottom: '1px solid rgba(255,255,255,0.08)', flexShrink: 0 }}>
          <div>
            <span style={{ fontFamily: "'Instrument Serif',serif", fontStyle: 'italic', fontSize: 22, color: '#fff' }}>Terms & Conditions</span>
            <span style={{ marginLeft: 12, fontFamily: "'Barlow',sans-serif", fontSize: 10, color: 'rgba(255,255,255,0.3)', textTransform: 'uppercase', letterSpacing: '0.08em' }}>Last updated: March 28, 2026</span>
          </div>
          <button onClick={onClose} style={{ background: 'rgba(255,255,255,0.08)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: 8, color: '#fff', fontFamily: "'Barlow',sans-serif", fontSize: 12, padding: '6px 14px', cursor: 'pointer' }}>✕ Close</button>
        </div>
        <div data-lenis-prevent style={{ flex: 1, overflowY: 'scroll', padding: '28px', overscrollBehavior: 'contain' }}>
          <div style={{ fontFamily: "'Barlow',sans-serif", fontWeight: 300, fontSize: 12, color: 'rgba(255,255,255,0.4)', lineHeight: 1.7, marginBottom: 24, padding: '12px 16px', background: 'rgba(251,191,36,0.06)', border: '1px solid rgba(251,191,36,0.15)', borderRadius: 10 }}>
            ⚠ This document is provided for informational purposes. These Terms govern your use of the Dwelling platform. By using the platform you agree to be bound by them.
          </div>
          {SECTIONS.map(({ title, body }) => (
            <div key={title} style={{ marginBottom: 24, paddingBottom: 24, borderBottom: '1px solid rgba(255,255,255,0.05)' }}>
              <div style={{ fontFamily: "'Instrument Serif',serif", fontStyle: 'italic', fontSize: 16, color: '#fff', marginBottom: 8 }}>{title}</div>
              <p style={{ fontFamily: "'Barlow',sans-serif", fontWeight: 300, fontSize: 13, color: 'rgba(255,255,255,0.6)', lineHeight: 1.85 }}>{body}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
